#!/bin/bash -exf
#
# Copyright (c) 2020 Institution of Parallel and Distributed System, Shanghai Jiao Tong University
# ServerlessBench is licensed under the Mulan PSL v1.
# You can use this software according to the terms and conditions of the Mulan PSL v1.
# You may obtain a copy of Mulan PSL v1 at:
#     http://license.coscl.org.cn/MulanPSL
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v1 for more details.
#

if [ $# -lt 1 ]; then
  echo "Usage: $(basename $0) DIRECTORY [FILTERS]"
  exit 1
fi

SRCDIR=$1
FILTERS_FILE=$2
NPROC=$(($(nproc)*2))

# HACK make sure gg dir is discoverable
gg-infer sh -c ':'

FIND_CMD=()

if [ ! -z "${FILTERS_FILE}" ]; then
  while read -r FILE
  do
    if [ ${#FIND_CMD[@]} -gt 0 ]; then
      FIND_CMD+=("-o")
    fi
    FIND_CMD+=("-ipath" "$FILE")
  done <${FILTERS_FILE}
else
  FIND_CMD=("-ipath" '*')
fi

function collect_directory {
  find ${SRCDIR} -type f \( ${FIND_CMD[@]} \) | xargs -P ${NPROC} -I% -- gg-collect "%"
}

collect_directory
