#!/usr/bin/env perl
#
# Copyright (c) 2020 Institution of Parallel and Distributed System, Shanghai Jiao Tong University
# ServerlessBench is licensed under the Mulan PSL v1.
# You can use this software according to the terms and conditions of the Mulan PSL v1.
# You may obtain a copy of Mulan PSL v1 at:
#     http://license.coscl.org.cn/MulanPSL
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v1 for more details.
#

#
# The sole function of this script is to provide a stdin that doesn't
# read data or return EOF to its children.  If there's a clean,
# portable, not-Perl way to do this, then that should replace this.
#
use warnings;
use strict;

my $pid = open(my $fh, "|-", @ARGV) or die;
waitpid($pid, 0) == $pid or die;
my $rc;
if ($? == 0) {
    $rc = 0;
} elsif ($? >= 256) {
    $rc = $? >> 8;
} else {
    $rc = ($? & 127) | 128;
}
exit $rc;
