#!/usr/bin/env perl
#
# Copyright (c) 2020 Institution of Parallel and Distributed System, Shanghai Jiao Tong University
# ServerlessBench is licensed under the Mulan PSL v1.
# You can use this software according to the terms and conditions of the Mulan PSL v1.
# You may obtain a copy of Mulan PSL v1 at:
#     http://license.coscl.org.cn/MulanPSL
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v1 for more details.
#

#
# Print exitstatus on stderr.
#
use warnings;
use strict;

my $rc = system(@ARGV);
if ($? == -1) {
    die "system failed: %!\n";
}
if ($? == 0) {
    $rc = 0;
} elsif ($? >= 256) {
    $rc = $? >> 8;
} else {
    $rc = ($? & 127) | 128;
}
print STDERR "@@@ exitstatus: ${rc} @@@\n";
# Now look for it in log file.
my $grepfilename = $ENV{'MOSH_E2E_TEST'} . ".tmux.log";
for my $i (1..600) {
    open(my $grepfile, "<", $grepfilename) or die;
    while (<$grepfile>) {
	chomp;
	/@@@ exitstatus: .* @@@/ && goto gotit;
    }
    close($grepfile);
    sleep .1;
}
 gotit:
exit $rc;
